//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriggerCommandLineConsoleTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriggerCommandLineConsoleTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   INFO] Forge tools running at version 3.3.71
        ///[   INFO] Creating Android .apk file
        ///[   INFO] Creating APK with aapt
        ///[   INFO] Signing APK with your release key
        ///[  ERROR] Failed when running java: Failed to load key, does the key exist?.
        /// </summary>
        internal static string BADANDPACKAGE {
            get {
                return ResourceManager.GetString("BADANDPACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   INFO] Forge tools running at version 3.3.71
        ///[   INFO] Update result: you already have the latest tools
        ///[   INFO] Checking JavaScript files...
        ///[   INFO] JavaScript check complete
        ///[   INFO] Verifying your configuration settings...
        ///[   INFO] Configuration settings check complete
        ///[   ERROR] Development build failed.
        /// </summary>
        internal static string BADBUILD {
            get {
                return ResourceManager.GetString("BADBUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   INFO] Forge tools running at version 3.3.71
        ///[   INFO] Starting package process for iOS
        ///[   INFO] Going to package: D:\development\ios\device-ios.app
        ///[   INFO] Plist OK
        ///[   INFO] 6 Provisioned Device(s):
        ///[  ERROR] Failed when running java: 2014-01-01 13:18:48.355 INFO: Loading certificate and private key.
        /// </summary>
        internal static string BADIOSPACKAGE {
            get {
                return ResourceManager.GetString("BADIOSPACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   INFO] Forge tools running at version 3.3.71
        ///[   INFO] Checking JavaScript files...
        ///[WARNING] D:\Trigger\Apps\testlocal\src\js\main.js(3): SyntaxError: missing } in
        /// compound statement
        ///[WARNING] {
        ///[WARNING] ^
        ///[WARNING]
        ///[   INFO] JavaScript check complete
        ///[   INFO] Verifying your configuration settings...
        ///[   INFO] Configuration settings check complete.
        /// </summary>
        internal static string BADSANITYCHECK {
            get {
                return ResourceManager.GetString("BADSANITYCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   INFO] Forge tools running at version 3.3.71
        ///[   INFO] Creating Android .apk file
        ///[   INFO] Creating APK with aapt
        ///[   INFO] Signing APK with your release key
        ///[   INFO] Aligning apk
        ///[   INFO] created APK: D:\1388611906.apk.
        /// </summary>
        internal static string GOODANDPACKAGE {
            get {
                return ResourceManager.GetString("GOODANDPACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   INFO] Forge tools running at version 3.3.71
        ///[   INFO] Update result: you already have the latest tools
        ///[   INFO] Checking JavaScript files...
        ///[   INFO] JavaScript check complete
        ///[   INFO] Verifying your configuration settings...
        ///[   INFO] Configuration settings check complete
        ///[   INFO] Development build created. Use forge run to run your app..
        /// </summary>
        internal static string GOODBUILD {
            get {
                return ResourceManager.GetString("GOODBUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   INFO] Forge tools running at version 3.3.71
        ///[   INFO] Starting package process for iOS
        ///[   INFO] Going to package: D:\development\ios\device-ios.app
        ///[   INFO] Plist OK
        ///[   INFO] 6 Provisioned Device(s):
        ///[   INFO] created IPA: D:\1388610920.ipa.
        /// </summary>
        internal static string GOODIOSPACKAGE {
            get {
                return ResourceManager.GetString("GOODIOSPACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [   INFO] Forge tools running at version 3.3.71
        ///[   INFO] Checking JavaScript files...
        ///[   INFO] JavaScript check complete
        ///[   INFO] Verifying your configuration settings...
        ///[   INFO] Configuration settings check complete.
        /// </summary>
        internal static string GOODSANITYCHECK {
            get {
                return ResourceManager.GetString("GOODSANITYCHECK", resourceCulture);
            }
        }
    }
}
